# See here for image description: https://github.com/envygeeks/jekyll-docker#readme

# Jekyll version should match that used by GitHub Pages: https://pages.github.com/versions/
# If no image on Docker Hub has that version, then use the closest version BELOW it
ARG RUBY_VERSION="2.7.3"
ARG PLATFORM="buster"
FROM ruby:$RUBY_VERSION-$PLATFORM

# ** [Optional] Uncomment this section to install additional packages. **
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
