source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
  # gem "<plugin>", "~> 1.0"
end

gem "webrick", "~> 1.7" # Apparently needed for live-reloading of local Jekyll server
