# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog,
# values which you are expected to set up once and rarely edit after that.
# If you find # yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site.
# If you look in the HTML files, you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible in the templates via {{ site.myvariable }}.

title: Derploid® Entertainment
isProduction: true  # Overridden to false in test repo
copyright:
  startYear: 2017
  endYear: 2025
  owner: Derploid® Entertainment, LLC
contact:
  twitter: DerploidCo
  github: DerploidEntertainment
  email: contact@derploid.com
  support: https://github.com/DerploidEntertainment/Website/issues/new
privacyPolicyUri: https://hhh-legal-docs.s3.us-east-2.amazonaws.com/hhh-privacy.html
highHandHoldem:
  productName: High Hand Hold'em™
  supportUri: https://github.com/DerploidEntertainment/HighHandHoldem-Support
appAds: # These values are NOT secrets, since they'll end up in the public app-ads.txt file anyway
  admobPublisherId: pub-4376011031523107
  facebookBusinessId: "767911241660206"
  yandexPartnerId: "104431884"

strict_front_matter: true
defaults:
  - scope: { path: "" }
    values:
      layout: default
  - scope: { path: "email/" }
    values:
      layout: simple-page

# Build settings
plugins: []

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or their entries' file path in the `include:` list.
#
include: []
exclude:
  - README.md
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
